### PR TITLE
py36 bump since there is a matching package in epel now

### LINKED ISSUE #49: py36 bump
Looking at how travis is failing on https://github.com/radiorabe/suisa_sendemeldung/pull/48 we should consider bumping to py36.

### PR DESCRIPTION
**Pull request by spameier**
fixes #49

### CODE REVIEW

**Comment by spameier** [comment]
When keeping `%check` the [build](https://build.opensuse.org/package/live_build_log/home:spameier:suisa_sendemeldung/suisa_sendemeldung/CentOS_7/x86_64) on OBS fails: 
```
[   85s] Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.4LRkyL
[   85s] + umask 022
[   85s] + cd /home/abuild/rpmbuild/BUILD
[   85s] + cd suisa_sendemeldung-1599292778.c42618c
[   85s] + /usr/bin/python3 setup.py test
[   85s] + /usr/lib/rpm/redhat/brp-java-repack-jars
[   85s] Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.4LRkyL
[   85s] + umask 022
[   85s] + cd /home/abuild/rpmbuild/BUILD
[   85s] + cd suisa_sendemeldung-1599292778.c42618c
[   85s] + /usr/bin/python3 setup.py test
[   85s] running test
[   85s] Searching for pytz
[   85s] Reading https://pypi.org/simple/pytz/
[   85s] Download error on https://pypi.org/simple/pytz/: [Errno -2] Name or service not known -- Some packages may not be found!
[   85s] Couldn't find index page for 'pytz' (maybe misspelled?)
[   85s] Scanning index of all packages (this may take a while)
[   85s] Reading https://pypi.org/simple/
[   85s] Download error on https://pypi.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
[   85s] No local packages or working download links found for pytz
[   85s] error: Could not find suitable distribution for Requirement.parse('pytz')
[   85s] error: Bad exit status from /var/tmp/rpm-tmp.4LRkyL (%check)
[   85s] 
[   85s] 
[   85s] RPM build errors:
[   85s]     Bad exit status from /var/tmp/rpm-tmp.4LRkyL (%check)
```

**Comment by hairmare** [comment]
> When keeping `%check` the [build](https://build.opensuse.org/package/live_build_log/home:spameier:suisa_sendemeldung/suisa_sendemeldung/CentOS_7/x86_64) on OBS fails:

OBS doesn't have internet access during the build. `%check` might work if you add `BuildRequires: python36-pytz` so it doesn't try to install pytz through pip.

**Comment by hairmare** [comment]
> OBS doesn't have internet access during the build. `%check` might work if you add `BuildRequires: python36-pytz` so it doesn't try to install pytz through pip.

**Comment by hairmare** [comment]
:uff: it looks like you already added a `Requires` for pytz which should suffice.

**Comment by spameier** [comment]
> :uff: it looks like you already added a `Requires` for pytz which should suffice.

No this actually solves the problem.
- [suisa_sendemeldung.spec](https://build.opensuse.org/package/view_file/home:spameier:suisa_sendemeldung/suisa_sendemeldung/_service:extract_file:suisa_sendemeldung.spec?expand=1)
- [log](https://build.opensuse.org/package/live_build_log/home:spameier:suisa_sendemeldung/suisa_sendemeldung/CentOS_7/x86_64)

**Review by hairmare — APPROVED** [review]

**Pull request merged**
